# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3bde8a17865d411179edb533be44e6d661fcff590089e06f3e4b1814c3dcbef4d15a9777cce8257eed5a434c7a944b54213e9a4d7e3a23acaaef6a2e429ca8b

test:
  secret_key_base: 96ba3a71bebf3b12a6575343deef110770b7ccad300cac908094fc623465871c4e9dc0cee6c20738c037140bcb22052818fa9fc7b8d25b837b4006115ee18113

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
